//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlVacuna.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Frasco
    {
        public long Id_Frasco { get; set; }
        public System.DateTime Fecha_Entrega { get; set; }
        public System.DateTime Fecha_Finalizacion { get; set; }
    }
}
