//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlVacuna.AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDControlVacunaEntities : DbContext
    {
        public BDControlVacunaEntities()
            : base("name=BDControlVacunaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Administrador> Administradors { get; set; }
        public DbSet<Frasco> Frascoes { get; set; }
        public DbSet<Paciente> Pacientes { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Vacuna> Vacunas { get; set; }
    }
}
