//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlVacuna.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacuna
    {
        public long Id_Vacuna { get; set; }
        public System.DateTime Fecha { get; set; }
        public long Id_Paciente { get; set; }
        public decimal Cantidad { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
